---
name: build

on:
  pull_request:
  push:
    # branches:
    #   - master

jobs:
  build:
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0']
        os:
          - 'ubuntu-latest'
          - 'windows-2019'
    runs-on: ${{ matrix.os }}
    name: Unit test with Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake build
